// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5VNQk6HwiG-leNWAtkeAorN-AzYned5A',
    appId: '1:1038305031669:web:91ced8fef6ce484ecd9cbc',
    messagingSenderId: '1038305031669',
    projectId: 'i-service-ca5e5',
    authDomain: 'i-service-ca5e5.firebaseapp.com',
    storageBucket: 'i-service-ca5e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpvQp1WDuayDLYejPt-caJ_D76jGDYA4',
    appId: '1:1038305031669:android:91b459224ff9ff7ecd9cbc',
    messagingSenderId: '1038305031669',
    projectId: 'i-service-ca5e5',
    storageBucket: 'i-service-ca5e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlsbg46BRlDvZ7mvglxc0tZpXysAUTlRo',
    appId: '1:1038305031669:ios:5c37ff1794412970cd9cbc',
    messagingSenderId: '1038305031669',
    projectId: 'i-service-ca5e5',
    storageBucket: 'i-service-ca5e5.appspot.com',
    iosBundleId: 'com.example.iService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlsbg46BRlDvZ7mvglxc0tZpXysAUTlRo',
    appId: '1:1038305031669:ios:c17cd923b956d595cd9cbc',
    messagingSenderId: '1038305031669',
    projectId: 'i-service-ca5e5',
    storageBucket: 'i-service-ca5e5.appspot.com',
    iosBundleId: 'com.example.iService.RunnerTests',
  );
}
